// A list of all actions in the system.
import { createTypes } from "reduxsauce";

export default createTypes(`

REQUEST_CONTACTS
RECEIVE_CONTACTS

CREATE_CONTACT_RECIEVE
CREATE_CONTACT_REQUEST

UPDATE_CONTACT_RECIEVE
UPDATE_CONTACT_REQUEST

DELETE_CONTACT_RECIEVE
DELETE_CONTACT_REQUEST

REQUEST_CONTACT
RECEIVE_CONTACT

`);
